mock_data_game = {
    "game:1:aaa": {"id": "1",
                   "player": "aaa",
                   "server": "QA服",
                   "startTime": "st1",
                   "durationTime": "10分",
                   "isConsistent": 0,
                   "operations": "查看详情",
                   "edition": "4001"
                   },
    "game:2:bbb": {"id": "2",
                   "player": "bbb",
                   "server": "公共服",
                   "startTime": "st2",
                   "durationTime": "8分6秒",
                   "isConsistent": 1,
                   "operations": "查看详情",
                   "edition": "4001"
                   },
    "game:3:ccc": {"id": "3",
                   "player": "ccc",
                   "server": "公共服",
                   "startTime": "st3",
                   "durationTime": "10分",
                   "isConsistent": 1,
                   "operations": "查看详情",
                   "edition": "4002"
                   },
    "game:4:ddd": {"id": "4",
                   "player": "ddd",
                   "server": "公共服",
                   "startTime": "st3",
                   "durationTime": "10分",
                   "isConsistent": 1,
                   "operations": "查看详情",
                   "edition": "4002"
                   },
    "game:5:eee": {"id": "1",
                   "player": "eee",
                   "server": "公共服",
                   "startTime": "st3",
                   "durationTime": "10分",
                   "isConsistent": 1,
                   "operations": "查看详情",
                   "edition": "4003"
                   },
    "game:6:fff": {"id": "6",
                   "player": "fff",
                   "server": "公共服",
                   "startTime": "st3",
                   "durationTime": "10分",
                   "isConsistent": 1,
                   "operations": "查看详情",
                   "edition": "4003"
                   }
}
