mock_data_game = {
    "game:1": {"id": 1,
               "players": [{"name": "aaa", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did", "stopFrame": "8000"},
                           {"name": "aaa2", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did",
                            "stopFrame": "8000"}],
               "server": "QA服",
               "startTime": "st1",
               "durationTime": "10分",
               "isConsistent": 0,
               "edition": "4001"
               },
    "game:2": {"id": 2,
               "players": [{"name": "bbb", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did", "stopFrame": "8000"},
                           {"name": "aaa2", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did",
                            "stopFrame": "8000"}],
               "server": "公共服",
               "startTime": "st2",
               "durationTime": "8分6秒",
               "isConsistent": 1,
               "edition": "4001"
               },
    "game:3": {"id": 3,
               "players": [{"name": "ccc", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did", "stopFrame": "8000"},
                           {"name": "aaa2", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did",
                            "stopFrame": "8000"}],
               "server": "公共服",
               "startTime": "st3",
               "durationTime": "10分",
               "isConsistent": 1,
               "edition": "4002"
               },
    "game:4": {"id": 4,
               "players": [{"name": "ddd", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did", "stopFrame": "8000"},
                           {"name": "aaa2", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did",
                            "stopFrame": "8000"}],
               "server": "公共服",
               "startTime": "st3",
               "durationTime": "10分",
               "isConsistent": 1,
               "edition": "4002"
               },
    "game:5": {"id": 5,
               "players": [{"name": "eee", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did", "stopFrame": "8000"},
                           {"name": "aaa2", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did",
                            "stopFrame": "8000"}],
               "server": "公共服",
               "startTime": "st3",
               "durationTime": "10分",
               "isConsistent": 1,
               "edition": "4003"
               },
    "game:6": {"id": 6,
               "players": [{"name": "fff", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did", "stopFrame": "8000"},
                           {"name": "aaa2", "appEdition": "0.666", "os": "Android", "osEdition": "11.4",
                            "deviceName": "xiaomi", "deviceType": "x50", "deviceId": "did",
                            "stopFrame": "8000"}],
               "server": "公共服",
               "startTime": "st3",
               "durationTime": "10分",
               "isConsistent": 1,
               "edition": "4003"
               }
}
